"""Create Cart#3

Revision ID: 6bdd3761e9c2
Revises: a4c7bcf9a751
Create Date: 2026-01-10 00:28:41.566076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdd3761e9c2'
down_revision: Union[str, Sequence[str], None] = 'a4c7bcf9a751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
